keycloak:
  realm: myrealm
  resource: myapp
  ssl-required: external
  auth-server-url: http://localhost:8082/
  use-resource-role-mappings: true

security:
  basic:
    enabled: false

server:
  port: 8085

app:
  keycloak:
    login:
      url: http://localhost:8082/realms/myrealm/protocol/openid-connect/token
    grant-type: password
    client-id: ${keycloak.resource}
    client-secret: ccyck2XBGJO7todBNFeyzIk5kEogbXZl







